INSTALLED_APPS += (
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    #'django.contrib.admindocs',
    #'desktop.filemanager',
    'objsys',
    'object_filter',
    'ui_framework',
    'ui_framework.collection_management',
    'tags',
    'ui_framework.connection',
    'ui_framework.normal_admin',
    'win_smb',
    'thumbapp',
    'guardian',
    'social_auth',
    'socialprofile',
    'smuggler',
    'registration',
    'registration_defaults',
    'pagination',
    'tagging',
    'south',
    'webmanage',
)