DEFAULT_DJANGO_MODULES = [
    "django.core.cache.backends.locmem",
    "django.core.serializers.xml_serializer",
    "django.core.serializers.python",
    "django.core.serializers.json",
    "django.core.serializers.pyyaml",
    'django.template.defaulttags',
    'django.template.defaultfilters',
    'django.template.loader_tags',
    'django.template.loaders.filesystem',
    'django.template.loaders.app_directories',
    'django.contrib.sessions.backends.db',
    'django.contrib.auth.models',
    'django.contrib.messages.storage.fallback',
    'django.contrib.sites',
    'django.contrib.sites.managers',
    'django.contrib.sites.management',
    'django.contrib.admin',
    'django.contrib.admin.models',
    'django.contrib.admin.sites',
    'django.contrib.admin.forms',
    "django.contrib.sessions",


    'django.db.models',
    'django.db.backends.sqlite3',
    "django.db.models.sql.compiler",
    "django.db.backends.postgresql_psycopg2",
    "django.db.backends.postgresql_psycopg2.base",

    'django.templatetags.i18n',
    'django.templatetags.l10n',
    'django.templatetags.static',
    'django.templatetags.cache',
    'django.templatetags.tz',
    'django.templatetags.future',
    'django.views.i18n',
    'django.views.csrf',
    'django.views.defaults',
    'django.views.static',
    'django.views.debug',
    'django.views.generic.simple',
    'django.conf.urls.defaults',
    'django.dispatch.dispatcher',

    #Needed when using cherrypy, copied from http://blog.robotercoding.com/?p=124
    'email.mime.audio',
    'email.mime.base',
    'email.mime.image',
    'email.mime.message',
    'email.mime.multipart',
    'email.mime.nonmultipart',
    'email.mime.text',
    'email.charset',
    'email.encoders',
    'email.errors',
    'email.feedparser',
    'email.generator',
    'email.header',
    'email.iterators',
    'email.message',
    'email.parser',
    'email.utils',
    'email.base64mime',
    'email.quoprimime',


    #"django.middleware.common",
    #"django.contrib.sessions.middleware",

    ##############
    #"allauth",
    #"allauth.account",
    "argparse",
    #"allauth.socialaccount",
    "guardian",
    "win_smb",
    "ui_framework",
    "collection_management",
    "normal_admin",
    "tags",
    "connection",
    "desktop.filemanager",
    #"thumbapp.views"
    "south.db.postgresql_psycopg2"
]