
gDefaultServices = ['monitor',
                'scache_storage',
                'tagged_enumerator',
                'tube_logging_service',
                'git_puller',
                're_send_service',
                'tag_exporter',
                'tag_importer',
                'delay_send_service',
                'domain_assign_service',
                #'folder_tagging',
                'all_tag_enumerator',
                'tube_folder_tagging',
                #'diagram_importer',
                'tag_enum',
                'file_moving_service',
                'drop_service',
                'kingsoft_disk',
                ]